/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AdditionalFormatsApplyConfiguration represents a declarative configuration of the AdditionalFormats type for use
// with apply.
//
// AdditionalFormats specifies any additional formats to write to the target
type AdditionalFormatsApplyConfiguration struct {
	// JKS requests a JKS-formatted binary trust bundle to be written to the target.
	// The bundle has "changeit" as the default password.
	// For more information refer to this link https://cert-manager.io/docs/faq/#keystore-passwords
	// Format is deprecated: Writing JKS is subject for removal. Please migrate to PKCS12.
	// PKCS#12 trust stores created by trust-manager are compatible with Java.
	JKS *JKSApplyConfiguration `json:"jks,omitempty"`
	// PKCS12 requests a PKCS12-formatted binary trust bundle to be written to the target.
	//
	// The bundle is by default created without a password.
	// For more information refer to this link https://cert-manager.io/docs/faq/#keystore-passwords
	PKCS12 *PKCS12ApplyConfiguration `json:"pkcs12,omitempty"`
}

// AdditionalFormatsApplyConfiguration constructs a declarative configuration of the AdditionalFormats type for use with
// apply.
func AdditionalFormats() *AdditionalFormatsApplyConfiguration {
	return &AdditionalFormatsApplyConfiguration{}
}

// WithJKS sets the JKS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JKS field is set to the value of the last call.
func (b *AdditionalFormatsApplyConfiguration) WithJKS(value *JKSApplyConfiguration) *AdditionalFormatsApplyConfiguration {
	b.JKS = value
	return b
}

// WithPKCS12 sets the PKCS12 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PKCS12 field is set to the value of the last call.
func (b *AdditionalFormatsApplyConfiguration) WithPKCS12(value *PKCS12ApplyConfiguration) *AdditionalFormatsApplyConfiguration {
	b.PKCS12 = value
	return b
}
