/*
Copyright 2023 The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BundleStatusApplyConfiguration represents an declarative configuration of the BundleStatus type for use
// with apply.
type BundleStatusApplyConfiguration struct {
	Conditions              []BundleConditionApplyConfiguration `json:"conditions,omitempty"`
	DefaultCAPackageVersion *string                             `json:"defaultCAVersion,omitempty"`
}

// BundleStatusApplyConfiguration constructs an declarative configuration of the BundleStatus type for use with
// apply.
func BundleStatus() *BundleStatusApplyConfiguration {
	return &BundleStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BundleStatusApplyConfiguration) WithConditions(values ...*BundleConditionApplyConfiguration) *BundleStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithDefaultCAPackageVersion sets the DefaultCAPackageVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultCAPackageVersion field is set to the value of the last call.
func (b *BundleStatusApplyConfiguration) WithDefaultCAPackageVersion(value string) *BundleStatusApplyConfiguration {
	b.DefaultCAPackageVersion = &value
	return b
}
