/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ConfigMapTargetApplyConfiguration represents a declarative configuration of the ConfigMapTarget type for use
// with apply.
//
// ConfigMapTarget defines the form of the Kubernetes ConfigMap bundle target.
type ConfigMapTargetApplyConfiguration struct {
	// key is the key of the entry in the object's `data` field to be used.
	Key *string `json:"key,omitempty"`
	// metadata is an optional set of labels and annotations to be copied to the target.
	Metadata *TargetMetadataApplyConfiguration `json:"metadata,omitempty"`
}

// ConfigMapTargetApplyConfiguration constructs a declarative configuration of the ConfigMapTarget type for use with
// apply.
func ConfigMapTarget() *ConfigMapTargetApplyConfiguration {
	return &ConfigMapTargetApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ConfigMapTargetApplyConfiguration) WithKey(value string) *ConfigMapTargetApplyConfiguration {
	b.Key = &value
	return b
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *ConfigMapTargetApplyConfiguration) WithMetadata(value *TargetMetadataApplyConfiguration) *ConfigMapTargetApplyConfiguration {
	b.Metadata = value
	return b
}
