{{- if .Values.startupapicheck.enabled -}}
{{- if .Values.startupapicheck.serviceAccount.create -}}
{{- $ann := dict "helm.sh/hook" "post-install,post-upgrade" "helm.sh/hook-weight" "-5" "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded" -}}
{{- with .Values.startupapicheck.serviceAccount.annotations -}}
{{- $ann = merge $ann . -}}
{{- end -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.startupapicheck.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "trust-manager.startupapicheck.serviceAccountName" . }}
  namespace: {{ include "trust-manager.namespace" . }}
  labels:
    app: {{ include "trust-manager.startupapicheck.name" . }}
{{- include "trust-manager.labels" . | nindent 4 }}
{{- with .Values.startupapicheck.serviceAccount.labels }}
{{- toYaml . | nindent 4 }}
{{- end }}
  annotations:
{{- toYaml $ann | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
