---
app:
  metrics:
    service:
      servicemonitor:
        enabled: true

        endpointAdditionalProperties:
          relabelings:
            - action: replace
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: instance
