/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BundleTargetApplyConfiguration represents a declarative configuration of the BundleTarget type for use
// with apply.
//
// BundleTarget is the target resource that the Bundle will sync all source
// data to.
type BundleTargetApplyConfiguration struct {
	// configMap is the target ConfigMap in Namespaces that all Bundle source data will be synced to.
	ConfigMap *KeyValueTargetApplyConfiguration `json:"configMap,omitempty"`
	// secret is the target Secret in Namespaces that all Bundle source data will be synced to.
	// Using Secrets as targets is only supported if enabled at trust-manager startup.
	// By default, trust-manager has no permissions for writing to secrets and can only read secrets in the trust namespace.
	Secret *KeyValueTargetApplyConfiguration `json:"secret,omitempty"`
	// namespaceSelector specifies the namespaces where target resources will be synced.
	NamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
}

// BundleTargetApplyConfiguration constructs a declarative configuration of the BundleTarget type for use with
// apply.
func BundleTarget() *BundleTargetApplyConfiguration {
	return &BundleTargetApplyConfiguration{}
}

// WithConfigMap sets the ConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMap field is set to the value of the last call.
func (b *BundleTargetApplyConfiguration) WithConfigMap(value *KeyValueTargetApplyConfiguration) *BundleTargetApplyConfiguration {
	b.ConfigMap = value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *BundleTargetApplyConfiguration) WithSecret(value *KeyValueTargetApplyConfiguration) *BundleTargetApplyConfiguration {
	b.Secret = value
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *BundleTargetApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *BundleTargetApplyConfiguration {
	b.NamespaceSelector = value
	return b
}
