/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	trustmanagerv1alpha2 "github.com/cert-manager/trust-manager/pkg/apis/trustmanager/v1alpha2"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BundleTargetApplyConfiguration represents a declarative configuration of the BundleTarget type for use
// with apply.
type BundleTargetApplyConfiguration struct {
	ConfigMap         *trustmanagerv1alpha2.KeyValueTarget `json:"configMap,omitempty"`
	Secret            *trustmanagerv1alpha2.KeyValueTarget `json:"secret,omitempty"`
	NamespaceSelector *v1.LabelSelectorApplyConfiguration  `json:"namespaceSelector,omitempty"`
}

// BundleTargetApplyConfiguration constructs a declarative configuration of the BundleTarget type for use with
// apply.
func BundleTarget() *BundleTargetApplyConfiguration {
	return &BundleTargetApplyConfiguration{}
}

// WithConfigMap sets the ConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMap field is set to the value of the last call.
func (b *BundleTargetApplyConfiguration) WithConfigMap(value trustmanagerv1alpha2.KeyValueTarget) *BundleTargetApplyConfiguration {
	b.ConfigMap = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *BundleTargetApplyConfiguration) WithSecret(value trustmanagerv1alpha2.KeyValueTarget) *BundleTargetApplyConfiguration {
	b.Secret = &value
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *BundleTargetApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *BundleTargetApplyConfiguration {
	b.NamespaceSelector = value
	return b
}
