/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BundleSourceApplyConfiguration represents a declarative configuration of the BundleSource type for use
// with apply.
//
// BundleSource is the set of sources whose data will be appended and synced to
// the BundleTarget in all Namespaces.
type BundleSourceApplyConfiguration struct {
	SourceReferenceApplyConfiguration `json:",inline"`
	// Key(s) of the entry in the object's `data` field to be used.
	// Wildcards "*" in Key matches any sequence characters.
	// A Key containing only "*" will match all data fields.
	Key *string `json:"key,omitempty"`
}

// BundleSourceApplyConfiguration constructs a declarative configuration of the BundleSource type for use with
// apply.
func BundleSource() *BundleSourceApplyConfiguration {
	return &BundleSourceApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithKind(value string) *BundleSourceApplyConfiguration {
	b.SourceReferenceApplyConfiguration.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithName(value string) *BundleSourceApplyConfiguration {
	b.SourceReferenceApplyConfiguration.Name = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *BundleSourceApplyConfiguration {
	b.SourceReferenceApplyConfiguration.Selector = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *BundleSourceApplyConfiguration) WithKey(value string) *BundleSourceApplyConfiguration {
	b.Key = &value
	return b
}
