/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

// BundleSpecApplyConfiguration represents a declarative configuration of the BundleSpec type for use
// with apply.
//
// BundleSpec defines the desired state of a Bundle.
type BundleSpecApplyConfiguration struct {
	// sourceRefs is a list of references to resources whose data will be appended and synced into
	// the bundle target resources.
	SourceRefs []BundleSourceRefApplyConfiguration `json:"sourceRefs,omitempty"`
	// includeDefaultCAs indicates whether the default CA bundle should be used as a source.
	// The default CA bundle is available only if trust-manager was installed with
	// default CA support enabled, either via the Helm chart or by starting the
	// trust-manager controller with the "--default-package-location" flag.
	// If default CA support was not enabled at startup, setting this field to true
	// will result in reconciliation failure.
	// The version of the default CA package used for this Bundle is reported in
	// status.defaultCAVersion.
	IncludeDefaultCAs *bool `json:"includeDefaultCAs,omitempty"`
	// inLineCAs is a simple string to append as the source data.
	InLineCAs *string `json:"inLineCAs,omitempty"`
	// target is the target location in all namespaces to sync source data to.
	Target *BundleTargetApplyConfiguration `json:"target,omitempty"`
}

// BundleSpecApplyConfiguration constructs a declarative configuration of the BundleSpec type for use with
// apply.
func BundleSpec() *BundleSpecApplyConfiguration {
	return &BundleSpecApplyConfiguration{}
}

// WithSourceRefs adds the given value to the SourceRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SourceRefs field.
func (b *BundleSpecApplyConfiguration) WithSourceRefs(values ...*BundleSourceRefApplyConfiguration) *BundleSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSourceRefs")
		}
		b.SourceRefs = append(b.SourceRefs, *values[i])
	}
	return b
}

// WithIncludeDefaultCAs sets the IncludeDefaultCAs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IncludeDefaultCAs field is set to the value of the last call.
func (b *BundleSpecApplyConfiguration) WithIncludeDefaultCAs(value bool) *BundleSpecApplyConfiguration {
	b.IncludeDefaultCAs = &value
	return b
}

// WithInLineCAs sets the InLineCAs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InLineCAs field is set to the value of the last call.
func (b *BundleSpecApplyConfiguration) WithInLineCAs(value string) *BundleSpecApplyConfiguration {
	b.InLineCAs = &value
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *BundleSpecApplyConfiguration) WithTarget(value *BundleTargetApplyConfiguration) *BundleSpecApplyConfiguration {
	b.Target = value
	return b
}
