/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BundleSourceRefApplyConfiguration represents a declarative configuration of the BundleSourceRef type for use
// with apply.
//
// BundleSourceRef is a reference to source resource(s) whose data will be appended and synced into
// the bundle target resources.
type BundleSourceRefApplyConfiguration struct {
	SourceReferenceApplyConfiguration `json:",inline"`
	// key specifies one or more keys in the object's data field to be used.
	// The "*" wildcard matches any sequence of characters within a key.
	// A value of "*" matches all entries in the data field.
	Key *string `json:"key,omitempty"`
}

// BundleSourceRefApplyConfiguration constructs a declarative configuration of the BundleSourceRef type for use with
// apply.
func BundleSourceRef() *BundleSourceRefApplyConfiguration {
	return &BundleSourceRefApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *BundleSourceRefApplyConfiguration) WithKind(value string) *BundleSourceRefApplyConfiguration {
	b.SourceReferenceApplyConfiguration.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BundleSourceRefApplyConfiguration) WithName(value string) *BundleSourceRefApplyConfiguration {
	b.SourceReferenceApplyConfiguration.Name = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *BundleSourceRefApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *BundleSourceRefApplyConfiguration {
	b.SourceReferenceApplyConfiguration.Selector = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *BundleSourceRefApplyConfiguration) WithKey(value string) *BundleSourceRefApplyConfiguration {
	b.Key = &value
	return b
}
