/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

// BundleSpecApplyConfiguration represents a declarative configuration of the BundleSpec type for use
// with apply.
//
// BundleSpec defines the desired state of a Bundle.
type BundleSpecApplyConfiguration struct {
	// Sources is a set of references to data whose data will sync to the target.
	Sources []BundleSourceApplyConfiguration `json:"sources,omitempty"`
	// IncludeDefaultCAs, when true, requests the default CA bundle to be used as a source.
	// Default CAs are available if trust-manager was installed via Helm
	// or was otherwise set up to include a package-injecting init container by using the
	// "--default-package-location" flag when starting the trust-manager controller.
	// If default CAs were not configured at start-up, any request to use the default
	// CAs will fail.
	// The version of the default CA package which is used for a Bundle is stored in the
	// defaultCAPackageVersion field of the Bundle's status field.
	IncludeDefaultCAs *bool `json:"includeDefaultCAs,omitempty"`
	// InLine is a simple string to append as the source data.
	InLineCAs *string `json:"inLineCAs,omitempty"`
	// Target is the target location in all namespaces to sync source data to.
	Target *BundleTargetApplyConfiguration `json:"target,omitempty"`
	// Use only CAs certificates in a resulting Bundle
	UseCACertsOnly *bool `json:"useCACertsOnly,omitempty"`
}

// BundleSpecApplyConfiguration constructs a declarative configuration of the BundleSpec type for use with
// apply.
func BundleSpec() *BundleSpecApplyConfiguration {
	return &BundleSpecApplyConfiguration{}
}

// WithSources adds the given value to the Sources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sources field.
func (b *BundleSpecApplyConfiguration) WithSources(values ...*BundleSourceApplyConfiguration) *BundleSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSources")
		}
		b.Sources = append(b.Sources, *values[i])
	}
	return b
}

// WithIncludeDefaultCAs sets the IncludeDefaultCAs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IncludeDefaultCAs field is set to the value of the last call.
func (b *BundleSpecApplyConfiguration) WithIncludeDefaultCAs(value bool) *BundleSpecApplyConfiguration {
	b.IncludeDefaultCAs = &value
	return b
}

// WithInLineCAs sets the InLineCAs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InLineCAs field is set to the value of the last call.
func (b *BundleSpecApplyConfiguration) WithInLineCAs(value string) *BundleSpecApplyConfiguration {
	b.InLineCAs = &value
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *BundleSpecApplyConfiguration) WithTarget(value *BundleTargetApplyConfiguration) *BundleSpecApplyConfiguration {
	b.Target = value
	return b
}

// WithUseCACertsOnly sets the UseCACertsOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseCACertsOnly field is set to the value of the last call.
func (b *BundleSpecApplyConfiguration) WithUseCACertsOnly(value bool) *BundleSpecApplyConfiguration {
	b.UseCACertsOnly = &value
	return b
}
