/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CertHistoryEntryApplyConfiguration represents a declarative configuration of the CertHistoryEntry type for use
// with apply.
//
// CertHistoryEntry holds a single historical CA certificate for a source.
type CertHistoryEntryApplyConfiguration struct {
	// pem is the PEM-encoded certificate.
	PEM *string `json:"pem,omitempty"`
	// notAfter is the expiry time parsed from the certificate.
	NotAfter *v1.Time `json:"notAfter,omitempty"`
	// addedAt is when this entry was recorded by trust-manager.
	AddedAt *v1.Time `json:"addedAt,omitempty"`
	// fingerprint is the SHA-256 of the DER-encoded cert, hex-encoded.
	// Used to detect duplicates across reconcile cycles.
	Fingerprint *string `json:"fingerprint,omitempty"`
}

// CertHistoryEntryApplyConfiguration constructs a declarative configuration of the CertHistoryEntry type for use with
// apply.
func CertHistoryEntry() *CertHistoryEntryApplyConfiguration {
	return &CertHistoryEntryApplyConfiguration{}
}

// WithPEM sets the PEM field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PEM field is set to the value of the last call.
func (b *CertHistoryEntryApplyConfiguration) WithPEM(value string) *CertHistoryEntryApplyConfiguration {
	b.PEM = &value
	return b
}

// WithNotAfter sets the NotAfter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotAfter field is set to the value of the last call.
func (b *CertHistoryEntryApplyConfiguration) WithNotAfter(value v1.Time) *CertHistoryEntryApplyConfiguration {
	b.NotAfter = &value
	return b
}

// WithAddedAt sets the AddedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AddedAt field is set to the value of the last call.
func (b *CertHistoryEntryApplyConfiguration) WithAddedAt(value v1.Time) *CertHistoryEntryApplyConfiguration {
	b.AddedAt = &value
	return b
}

// WithFingerprint sets the Fingerprint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fingerprint field is set to the value of the last call.
func (b *CertHistoryEntryApplyConfiguration) WithFingerprint(value string) *CertHistoryEntryApplyConfiguration {
	b.Fingerprint = &value
	return b
}
