/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

// DefaultCAsSourceApplyConfiguration represents a declarative configuration of the DefaultCAsSource type for use
// with apply.
//
// DefaultCAsSource configures the use of a default CA bundle as a trust source.
type DefaultCAsSourceApplyConfiguration struct {
	// provider identifies the provider of the default CA bundle.
	//
	// Valid values:
	// - System: Uses the default CA package made available to trust-manager at startup.
	// The default CA bundle is available only if trust-manager was installed with
	// default CA support enabled, either via the Helm chart or by starting the
	// trust-manager controller with the "--default-package-location" flag.
	//
	// If no default CA package was configured at startup, specifying this source
	// will result in reconciliation failure.
	//
	// The version of the default CA package used for this Bundle is reported in
	// status.defaultCAVersion.
	// - Disabled: No default CAs are used as sources.
	Provider *string `json:"provider,omitempty"`
}

// DefaultCAsSourceApplyConfiguration constructs a declarative configuration of the DefaultCAsSource type for use with
// apply.
func DefaultCAsSource() *DefaultCAsSourceApplyConfiguration {
	return &DefaultCAsSourceApplyConfiguration{}
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *DefaultCAsSourceApplyConfiguration) WithProvider(value string) *DefaultCAsSourceApplyConfiguration {
	b.Provider = &value
	return b
}
