/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	trustmanagerv1alpha2 "github.com/cert-manager/trust-manager/pkg/apis/trustmanager/v1alpha2"
)

// PKCS12ApplyConfiguration represents a declarative configuration of the PKCS12 type for use
// with apply.
type PKCS12ApplyConfiguration struct {
	KeySelectorApplyConfiguration `json:",inline"`
	Password                      *string                             `json:"password,omitempty"`
	Profile                       *trustmanagerv1alpha2.PKCS12Profile `json:"profile,omitempty"`
}

// PKCS12ApplyConfiguration constructs a declarative configuration of the PKCS12 type for use with
// apply.
func PKCS12() *PKCS12ApplyConfiguration {
	return &PKCS12ApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *PKCS12ApplyConfiguration) WithKey(value string) *PKCS12ApplyConfiguration {
	b.KeySelectorApplyConfiguration.Key = &value
	return b
}

// WithPassword sets the Password field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Password field is set to the value of the last call.
func (b *PKCS12ApplyConfiguration) WithPassword(value string) *PKCS12ApplyConfiguration {
	b.Password = &value
	return b
}

// WithProfile sets the Profile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Profile field is set to the value of the last call.
func (b *PKCS12ApplyConfiguration) WithProfile(value trustmanagerv1alpha2.PKCS12Profile) *PKCS12ApplyConfiguration {
	b.Profile = &value
	return b
}
