/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SourceReferenceApplyConfiguration represents a declarative configuration of the SourceReference type for use
// with apply.
//
// SourceReference is a reference to a source object.
type SourceReferenceApplyConfiguration struct {
	// kind is the kind of the source object.
	Kind *string `json:"kind,omitempty"`
	// name is the name of the source object in the trust namespace.
	// This field must be left empty when `selector` is set
	Name *string `json:"name,omitempty"`
	// selector is the label selector to use to fetch a list of objects. Must not be set
	// when `name` is set.
	Selector *v1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
}

// SourceReferenceApplyConfiguration constructs a declarative configuration of the SourceReference type for use with
// apply.
func SourceReference() *SourceReferenceApplyConfiguration {
	return &SourceReferenceApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *SourceReferenceApplyConfiguration) WithKind(value string) *SourceReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SourceReferenceApplyConfiguration) WithName(value string) *SourceReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *SourceReferenceApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *SourceReferenceApplyConfiguration {
	b.Selector = value
	return b
}
