/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

// SourceCertHistoryApplyConfiguration represents a declarative configuration of the SourceCertHistory type for use
// with apply.
//
// SourceCertHistory tracks the current and historical certificates for a source
// with keepCertHistory enabled.
type SourceCertHistoryApplyConfiguration struct {
	// sourceKey is a stable identifier for this source (e.g. "secret/my-ca/ca.crt").
	SourceKey *string `json:"sourceKey,omitempty"`
	// lastSeenFingerprint is the SHA-256 fingerprint of the most recently observed
	// current certificate from this source. Used to detect when rotation has occurred.
	LastSeenFingerprint *string `json:"lastSeenFingerprint,omitempty"`
	// lastSeenPEM is the PEM-encoded form of the most recently observed
	// current certificate. Stored so it can be moved to entries on rotation.
	LastSeenPEM *string `json:"lastSeenPEM,omitempty"`
	// entries is the list of historical (replaced) certificates, most recent first.
	Entries []CertHistoryEntryApplyConfiguration `json:"entries,omitempty"`
}

// SourceCertHistoryApplyConfiguration constructs a declarative configuration of the SourceCertHistory type for use with
// apply.
func SourceCertHistory() *SourceCertHistoryApplyConfiguration {
	return &SourceCertHistoryApplyConfiguration{}
}

// WithSourceKey sets the SourceKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceKey field is set to the value of the last call.
func (b *SourceCertHistoryApplyConfiguration) WithSourceKey(value string) *SourceCertHistoryApplyConfiguration {
	b.SourceKey = &value
	return b
}

// WithLastSeenFingerprint sets the LastSeenFingerprint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSeenFingerprint field is set to the value of the last call.
func (b *SourceCertHistoryApplyConfiguration) WithLastSeenFingerprint(value string) *SourceCertHistoryApplyConfiguration {
	b.LastSeenFingerprint = &value
	return b
}

// WithLastSeenPEM sets the LastSeenPEM field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSeenPEM field is set to the value of the last call.
func (b *SourceCertHistoryApplyConfiguration) WithLastSeenPEM(value string) *SourceCertHistoryApplyConfiguration {
	b.LastSeenPEM = &value
	return b
}

// WithEntries adds the given value to the Entries field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Entries field.
func (b *SourceCertHistoryApplyConfiguration) WithEntries(values ...*CertHistoryEntryApplyConfiguration) *SourceCertHistoryApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEntries")
		}
		b.Entries = append(b.Entries, *values[i])
	}
	return b
}
