# Copyright 2022 The cert-manager Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.21 as gobuild

ARG GOPROXY
ARG TARGETARCH

WORKDIR /work

COPY go.mod go.mod
COPY go.sum go.sum
COPY main.go main.go

RUN GOPROXY=$GOPROXY CGO_ENABLED=0 GOARCH=$TARGETARCH go build -o copyandmaybepause main.go

RUN GOPROXY=$GOPROXY go get github.com/cert-manager/trust-manager/cmd/validate-trust-package && GOPROXY=$GOPROXY CGO_ENABLED=0 GOARCH=$TARGETARCH go build -o /go/bin/validate-trust-package github.com/cert-manager/trust-manager/cmd/validate-trust-package

FROM docker.io/library/debian:11-slim as debbase

ARG EXPECTED_VERSION
ARG VERSION_SUFFIX

WORKDIR /work

COPY ./build.sh /work/build.sh
COPY --from=gobuild /go/bin/validate-trust-package /usr/bin/validate-trust-package

RUN /work/build.sh $EXPECTED_VERSION $VERSION_SUFFIX /work/package.json

FROM scratch

ARG EXPECTED_VERSION
ARG VERSION_SUFFIX

LABEL description="cert-manager trust package based on Debian"

USER 1001

COPY --from=debbase /usr/bin/tini-static /tini
COPY --from=debbase /work/package.json /debian-package/cert-manager-package-debian.json
COPY --from=gobuild /work/copyandmaybepause /copyandmaybepause

ENTRYPOINT ["/tini", "--"]

CMD ["/copyandmaybepause", "/debian-package", "/packages"]
