# Copyright 2024 The cert-manager Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated by the learn_kind_images.sh script in the makefile-modules repo.
# Do not edit manually.

kind_image_kindversion := v0.25.0

kind_image_kube_1.26_amd64 := docker.io/kindest/node:v1.26.15@sha256:70c6ccbd3ed58116ad489691148e0437d390ae4349d6990b9aa3863b5c5cc508
kind_image_kube_1.26_arm64 := docker.io/kindest/node:v1.26.15@sha256:83d636689f447921fdf13439391b252eebf471329f3d28a565d5a1a446d73cf7
kind_image_kube_1.27_amd64 := docker.io/kindest/node:v1.27.16@sha256:9a08bfb799b90527eb58f0c3ac54252c3578d93758bae768e975f1bd7ba3bca0
kind_image_kube_1.27_arm64 := docker.io/kindest/node:v1.27.16@sha256:637860d14e28d47c3ef1fe85bed7962a89269dfe6cb0fc6984fa98d61735a54e
kind_image_kube_1.28_amd64 := docker.io/kindest/node:v1.28.15@sha256:af665d70820b816eb1384b9f715f608dca9c625014ebbfa59415dcf703860e93
kind_image_kube_1.28_arm64 := docker.io/kindest/node:v1.28.15@sha256:4659eb060ae96f79dd9f66a54671dc5a6cd3ca83c7bdd765ad13c76dae510b18
kind_image_kube_1.29_amd64 := docker.io/kindest/node:v1.29.10@sha256:f2dc4d5c4a2ccbeadbc4da7e897710ccbf89c098c534c5850fcc26f6e91af81c
kind_image_kube_1.29_arm64 := docker.io/kindest/node:v1.29.10@sha256:0b6b641e44a02f75c3b6607de82598bdb5972c9f4b01572f2e7ecb32f717b35a
kind_image_kube_1.30_amd64 := docker.io/kindest/node:v1.30.6@sha256:2f2a7cddf4080e72da3c12372e6895027c6829df83f5ba3c4c9f1b4acd132aa6
kind_image_kube_1.30_arm64 := docker.io/kindest/node:v1.30.6@sha256:211095e72afdd11964c0afca8a891a60e66e523aac9f3fff2b87ece71eedf8ba
kind_image_kube_1.31_amd64 := docker.io/kindest/node:v1.31.2@sha256:0526eb5cd8d892ed79b56feb48d17eeee1f719f55d5c35cef468f053caffad32
kind_image_kube_1.31_arm64 := docker.io/kindest/node:v1.31.2@sha256:d60ac67de1482e71ea626ac98556cf5833c5c4bdedcf92ea158df61ea9eeaf5e
kind_image_kube_1.32_amd64 := docker.io/kindest/node:v1.32.0@sha256:dbfe3fe9f25dc234af268f5ac9a945e421ac43a30df02acae8c98224523f89f1
kind_image_kube_1.32_arm64 := docker.io/kindest/node:v1.32.0@sha256:4487ecad11a7bba166ab8781c5f5e914f33fb13215c6cacf8a9ce93e33c56923

kind_image_latest_amd64 := $(kind_image_kube_1.32_amd64)
kind_image_latest_arm64 := $(kind_image_kube_1.32_arm64)
