# Run trivy scans on the trust package container images every night.
name: trust-package-security-scan
on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: read

jobs:
  trust-package-security-scan:
    strategy:
      fail-fast: false
      matrix:
        release: [bullseye, bookworm, trixie]

    runs-on: ubuntu-latest

    if: github.repository == 'cert-manager/trust-manager'

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        # Adding `fetch-depth: 0` makes sure tags are also fetched. We need
        # the tags so `git describe` returns a valid version.
        # see https://github.com/actions/checkout/issues/701 for extra info about this option
        with: { fetch-depth: 0 }

      - run: make scan-debian-${{ matrix.release }}-trust-package
