name: trust-package-upgrade-debian-bookworm
concurrency: trust-package-upgrade-debian-bookworm
on:
  workflow_dispatch: {}
  schedule:
    - cron: '1 1 * * *'

jobs:
  upgrade:
    uses: ./.github/workflows/trust-package-upgrade.yaml
    with:
      distro: bookworm
    secrets: inherit
