name: trust-package-upgrade-debian-bullseye
concurrency: trust-package-upgrade-debian-bullseye
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  upgrade:
    uses: ./.github/workflows/trust-package-upgrade.yaml
    permissions:
      contents: write
      pull-requests: write
    with:
      distro: bullseye
    secrets: inherit
