name: trust-package-release-debian-bullseye
on:
  push:
    branches: ['main']
    paths:
      - make/00_debian_bullseye_version.mk

jobs:
  release:
    uses: ./.github/workflows/trust-package-release.yaml
    permissions:
      contents: read # needed for checkout
      packages: write # needed for push images
      id-token: write # needed for keyless signing
    with:
      distro: bullseye
    secrets: inherit
