name: trust-package-release-debian-trixie
on:
  push:
    branches: ['main']
    paths:
      - make/00_debian_trixie_version.mk

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read # needed for checkout
      packages: write # needed for push images
      id-token: write # needed for keyless signing

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        # Adding `fetch-depth: 0` makes sure tags are also fetched. We need
        # the tags so `git describe` returns a valid version.
        # see https://github.com/actions/checkout/issues/701 for extra info about this option
        with: { fetch-depth: 0 }

      - id: go-version
        run: |
          make print-go-version >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ steps.go-version.outputs.result }}

      - id: release
        run: make release-debian-trixie-trust-package

    outputs:
      RELEASE_OCI_MANAGER_IMAGE: ${{ steps.release.outputs.RELEASE_OCI_PACKAGE_DEBIAN_TRIXIE_IMAGE }}
      RELEASE_OCI_MANAGER_TAG: ${{ steps.release.outputs.RELEASE_OCI_PACKAGE_DEBIAN_TRIXIE_TAG }}
