name: trust-package-release-debian-bullseye
on:
  push:
    branches: ['main']
    paths:
      - make/00_debian_bullseye_version.mk

jobs:
  release:
    uses: ./.github/workflows/trust-package-release.yaml
    with:
      distro: bullseye
    secrets: inherit
